pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "aleja254/devops_udemy_billing"
    }

    stages {
        stage('Build JAR') {
            steps {
                // Cambiar 'sh' por 'bat' para Windows
                bat 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Cambiar 'sh' por 'bat' si el entorno es Windows
                    dockerImage = docker.build("${DOCKER_IMAGE}:latest")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASS')]) {
                    // Cambiar 'sh' por 'bat' para el login y push de Docker
                    bat "echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin"
                    bat "docker push ${DOCKER_IMAGE}:latest"
                }
            }
        }
    }

    post {
        always {
            echo '✔️ Pipeline finalizado'
        }
        failure {
            echo '❌ Falló la construcción o publicación de la imagen Docker.'
        }
    }
}